# File automatically generated by Transformer v1.3.0:
# https://github.com/zalando-incubator/Transformer
import re
from distutils.version import LooseVersion
from locust import __version__
LOCUST_MAJOR_VERSION = LooseVersion(__version__).version[0]
if LOCUST_MAJOR_VERSION >= 1:
    from locust import HttpUser
    from locust import SequentialTaskSet
    from locust import TaskSet
    from locust import task
    HttpLocust = HttpUser
    TaskSequence = SequentialTaskSet
    def seq_task(_):
        return task
else:
    from locust import HttpLocust
    from locust import TaskSequence
    from locust import TaskSet
    from locust import seq_task
    from locust import task
class HAR_files_testcase_1065420550(TaskSet):
    @task(1)
    class Scoodle_Path_Dashboard_Create_Class_And_Configure(TaskSequence):
        @seq_task(1)
        def GET_http_Bestand(self):
            response = self.client.get(url='https://locust.io/', name='Get Bestand ', timeout=30, allow_redirects=False, headers={'Host': 'locust.io/', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'Sec-Fetch-User': '?1', 'Referer': 'https://locust.io/', 'Accept-Encoding': 'gzip, deflate, br'})

class LocustForHAR_files_testcase_1065420550(HttpLocust):
    if LOCUST_MAJOR_VERSION >= 1:
        tasks = [HAR_files_testcase_1065420550]
    else:
        task_set = HAR_files_testcase_1065420550
    weight = 1
    min_wait = 0
    max_wait = 10